#
# Example API
#
put:
  path: /values/{key}
  controller: App\Controller\PutValueController
  methods: ["PUT"]

delete:
  path: /values/{key}
  controller: App\Controller\DeleteValueController
  methods: ["DELETE"]

get:
  path: /values/{key}
  controller: App\Controller\GetValueController
  methods: ["GET"]

#
# Example API
#
login:
  path: /login/
  controller: App\Controller\AuthController::login
  methods: ["POST"]

login:
  path: /logout/
  controller: App\Controller\AuthController::login
  methods: ["POST"]

#
# Public
#
view_values:
  path: /
  controller: App\Controller\IndexController
  methods: GET

test:
  path: /test
  controller: App\Controller\TestController
  methods: GET
